deepakkhokhar07/alisthub

public/modules/step_event/controller.js, public/modules/step_event/views/create_event_step1.html
Add bundle and add product popup design and event controller comment
=> Add bundle and add product popup design and event controller comment

app/event_setting/controllers/discount.js
=> updated discount

app/event_setting/controllers/venue.js, public/modules/step_event/controller.js, public/modules/step_event/views/create_event_step1.html
add bundle three steps on event page step 3
=> add bundle three steps

app/event/controllers/event.js, app/event_setting/controllers/bundle.js, public/javascripts/constants.js, public/modules/step_event/controller.js, public/modules/step_event/service.js, public/modules/step_event/views/create_event_step1.html, routes/event_setting.js
add bundle data saving and listing
=> add bundle data saving and listing

public/modules/step_event/controller.js, public/modules/step_event/views/create_event_step1.html
add bundle steps data and listing
=> add bundle steps data and listing

public/javascripts/app.js, public/javascripts/constants.js, public/modules/account/account_controller.js, public/modules/account/views/user/add_financial_setting.html, public/modules/account/views/user/custom_financial_setting.html, public/modules/authentication/controller.js, public/modules/authentication/views/login.html, public/modules/authentication/views/signup.html
bug fixing as suggested by maninder sir
=> bug fixing as suggested by maninder sir

app/event_setting/controllers/bundle.js, public/javascripts/constants.js, public/modules/step_event/controller.js, public/modules/step_event/service.js, public/modules/step_event/views/create_event_step1.html, routes/event_setting.js
Bundle listing change status/delete bundle and edit(in progress)
=> Bundle listing change status/delete bundle and edit(in progress)

app/account/controllers/account.js, public/javascripts/app.js, public/javascripts/constants.js, public/modules/account/account_controller.js, public/modules/account/service.js, public/modules/account/views/user/custom_financial_setting.html, public/modules/account/views/user/view_custom_financial_setting.html, public/modules/event_setting/views/discount/add_discount.html, public/stylesheets/style.css, routes/account.js
merchants custom financial settings
=> merchants custom financial settings

public/index.html
=> remove head

public/modules/step_event/controller.js
=> conflict resolved2

public/modules/step_event/controller.js
Bundle step 2 and 3 completed may 20
=> Bundle step 2 and 3 completed may 20

app/event_setting/controllers/bundle.js, public/javascripts/app.js, public/modules/step_event/service.js, public/modules/step_event/views/create_event_step1.html
=> Corrected errors

public/modules/event_setting/views/product/add_product.html, public/modules/event_setting/views/venue/add_venue.html, public/modules/event_setting/views/venue/view_venues.html, public/modules/manage/views/user/user.html, public/modules/step_event/views/pricelevelhtml.html
=> bug fixing

app/event_setting/controllers/product.js, public/modules/step_event/views/create_event_step1.html
=> create event page merge

app/event_setting/controllers/bundle.js, app/event_setting/controllers/product.js, public/javascripts/constants.js, public/modules/step_event/controller.js, public/modules/step_event/service.js, public/modules/step_event/views/bundlehtml.html, public/modules/step_event/views/step2.html, routes/event_setting.js
Add product and edit and listing
=> Add product and edit and listing

public/modules/event_setting/product_controller.js, public/modules/event_setting/views/bundle/view_bundle.html, public/modules/event_setting/views/discount/view_discount.html, public/modules/event_setting/views/product/product_overview.html, public/modules/event_setting/views/product/view_product.html, public/modules/event_setting/views/question/view_question.html, public/modules/event_setting/views/venue/venue_overview.html, public/modules/event_setting/views/venue/view_venues.html, public/stylesheets/style.css
=> back button in listing pages

npm-debug.log, public/modules/step_event/step2/controller.js, public/modules/step_event/step2/views/create_event_step2.html
corrected page setup for bundle and product
=> corrected page setup for bundle and product

app/event_setting/controllers/bundle.js, public/modules/step_event/service.js, public/modules/step_event/step2/controller.js, routes/event_setting.js
=> Edit second step for bundle 

app/event/controllers/event.js, npm-debug.log, public/modules/step_event/controller.js, public/modules/step_event/step2/controller.js, public/modules/step_event/views/create_event_step1.html
Edit event venue list and first step
=> Edit event venue list and first step

app/event/controllers/event.js, npm-debug.log, public/javascripts/app.js, public/javascripts/constants.js, public/modules/step_event/controller.js, public/modules/step_event/step2/controller.js, public/modules/step_event/step2/views/create_event_step2.html, public/modules/step_event/step3/controller.js, public/modules/step_event/step4/controller.js, public/modules/step_event/views/create_event_step1.html
edit event mangement, field created for step 4, top tab validation, save data on next step1
=> edit event mangement, field created for step 4, top tab validation, save data on next step1

app.js, app/event/controllers/event.js, app/event_package/controllers/package.js, npm-debug.log, public/javascripts/app.js, public/javascripts/constants.js, public/modules/event_package/controller_backup.js, public/modules/event_package/event_package_backup.html, public/modules/event_package/service.js, public/modules/event_package/step1/controller.js, public/modules/event_package/step1/views/event_package_step_1.html, public/modules/event_package/step2/controller.js, public/modules/event_package/step2/views/event_package_step_2.html, public/modules/event_package/step3/controller.js, public/modules/event_package/step3/service.js, public/modules/event_package/step3/views/event_package_step_3.html, public/modules/event_setting/discount_controller.js, routes/package.js
create event package code - in progess
=> create event package code - in progess

public/modules/step_event/step4/controller.js
Step 2 on blur change and step 4 - 2
=> Step 2 on blur change and step 4 - 2

public/modules/step_event/step4/controller.js
fixed issues related to the step 4 while testing
=> fixed issues related to the step 4 while testing 

npm-debug.log, public/modules/step_event/controller.js, public/modules/step_event/step2/controller.js, public/modules/step_event/step3/controller.js, public/modules/step_event/step4/controller.js
Fixed project review issue sent12
=> Fixed project review issue sent12

public/modules/events/controller.js, public/modules/events/views/dashboard.html, public/modules/step_event/controller.js, public/modules/step_event/step3/controller.js, public/modules/step_event/step4/controller.js
Worked on event schedule listing and dashboard links
=> Worked on event schedule listing and dashboard links

app/event/controllers/allevent.js, npm-debug.log, public/modules/events/allevent_controller.js, public/modules/events/controller.js, public/modules/events/event_schedule_controller.js, public/modules/events/views/dashboard.html, public/modules/events/views/view_event.html
Event view and linking schedule update
=> Event view and linking schedule update

app/event/controllers/allevent.js, public/modules/events/views/event_schedule_list.html, public/modules/events/views/view_event.html
Event view and linking schedule update3
=> Event view and linking schedule update3

app/event/controllers/event.js, public/modules/step_event/step2/controller.js, public/modules/step_event/step2/views/create_event_step2.html
=> second step ages

app/event/controllers/event.js, app/manage/controllers/user.js, public/javascripts/constants.js, public/modules/authentication/controller.js, public/modules/authentication/showclix_services.js, public/modules/events/controller.js, routes/seller_user.js
Worked on the login from the seller user profile
=> Worked on the login from the seller user profile  

app/event/controllers/event.js, public/modules/events/views/view_event.html
permision module uploaded conflicts
=> permision module uploaded conflicts

app/event_package/controllers/package.js, app/showclix/showclix_package.js, public/javascripts/constants.js, public/modules/event_package/step3/controller.js, public/modules/event_package/step3/views/event_package_step_3.html
=> showclix package api test

app/event_package/controllers/package.js, app/showclix/showclix_package.js
=> sclix delete

public/javascripts/app.js, public/modules/events/views/dashboard.html, public/modules/reports/controller.js, public/modules/reports/service.js, public/modules/reports/views/report.html
Created the report page and filtering
=> Created the report page and filtering

public/modules/event_series/step4/controller.js, public/modules/event_series/step4/views/create_series_step4.html, public/modules/step_event/step4/views/create_event_step4.html
=> step 4 series
